{{- define "dsk.kube-state-agent" -}}
- name: {{ .Values.dataSaker.kubeStateAgent.kind }}
  image: {{ .Values.dataSaker.registryAddr }}/{{ .Values.dataSaker.kubeStateAgent.kind }}:{{ .Values.dataSaker.kubeStateAgent.imgVersion }}
  imagePullPolicy: {{ .Values.dataSaker.kubeStateAgent.imgPolicy }}
  resources:
{{ toYaml .Values.dataSaker.kubeStateAgent.resources | indent 4 }}
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8080
    initialDelaySeconds: 5
    timeoutSeconds: 5
  ports:
    - containerPort: 8080
      name: http-metrics
    - containerPort: 8081
      name: telemetry
  readinessProbe:
    httpGet:
      path: /
      port: 8081
    initialDelaySeconds: 5
    timeoutSeconds: 5
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 0
    capabilities:
      drop:
        - ALL
  env:
    - name: DSK_LOG_LEVEL
      value: {{ .Values.dataSaker.kubeStateAgent.logLevel }}
  volumeMounts:
{{ toYaml .Values.default.volumeMounts | indent 4 }}
    - name: agent-config
      subPath: dsk-k8s-config.yml
      mountPath: {{ .Values.dataSaker.configDir }}/{{ .Values.dataSaker.kubeStateAgent.kind }}/agent-config.yml
{{- end -}}