---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dsk-k8s-agents
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: dsk-k8s-agents
data:
  dsk-k8s-config.yml: |
    agent:
      agent_name: dsk-k8s-agent
      cluster_id: {{ .Values.dataSaker.clusterId }}
      scrape_interval: 15s
      scrape_timeout: 5s
      external_labels:
        cluster_id: {{ .Values.dataSaker.clusterId }}
      scrape_configs:
        - job_name: dsk-k8s-agent
          url: localhost:9110
{{ toYaml .Values.default.metricConfig | indent 10 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: datasaker
    app.kubernetes.io/instance: dsk-k8s-agents
    app.kubernetes.io/version: 2.5.0
  name: dsk-k8s-agents
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datasaker
      app.kubernetes.io/instance: dsk-k8s-agents
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: datasaker
        app.kubernetes.io/instance: dsk-k8s-agents
        app.kubernetes.io/version: 2.5.0
    spec:
      automountServiceAccountToken: true
      containers:
{{ include "dsk.k8s-agent" . | indent 8 }}
{{ include "dsk.kube-state-agent" . | indent 8 }}
      volumes:
{{ toYaml .Values.default.volumes | indent 8 }}
        - name: agent-config
          configMap:
            name: dsk-k8s-agents
            items:
              - key: dsk-k8s-config.yml
                path: dsk-k8s-config.yml
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: dsk-k8s-agents
---