---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-global-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: agent-global-config
data:
  global-config.yml: |
    global:
      api_key: {{ .Values.dataSaker.apiKey }}
      datagates:
        metric_datagate:
          url: {{ .Values.dataSaker.metricDataGate }}
          remote_timeout: 5s
        manifest_datagate:
          url: {{ .Values.dataSaker.manifestDataGate }}
          remote_timeout: 5s
        jaeger_datagate:
          url: {{ .Values.dataSaker.jaegerDataGate }}
          remote_timeout: 5s
        plan_datagate:
          url: {{ .Values.dataSaker.planDataGate }}
          remote_timeout: 5s
      loggate:
        url: {{ .Values.dataSaker.logGate }}
        remote_timeout: 5s
      agent_manager:
        url: {{ .Values.dataSaker.agentManager }}
        base_url: {{ .Values.dataSaker.agentManagerBaseUrl }}
        send_interval: 1m
---