---
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-agent-configs
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: node-agent-configs
data:
  node-agent-config.yml: |
    agent:
      agent_name: {{ .Values.dataSaker.nodeAgent.kind }}
      scrape_interval: 15s
      scrape_timeout: 5s
      external_labels:
        cluster_id: {{ .Values.dataSaker.clusterId }}
      scrape_configs:
        - job_name: dsk-node-agent
          url: localhost:9110
{{ toYaml .Values.default.metricConfig | indent 10 }}
  container-agent-config.yml: |
    agent:
      agent_name: {{ .Values.dataSaker.containerAgent.kind }}
      scrape_interval: 15s
      scrape_timeout: 5s
      external_labels:
        cluster_id: {{ .Values.dataSaker.clusterId }}
      scrape_configs:
        - job_name: dsk-container-agent
          url: localhost:4194
{{ toYaml .Values.default.metricConfig | indent 10 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dsk-host-agents
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: dsk-host-agents
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: datasaker
      app: dsk-host-agents
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datasaker
        app: dsk-host-agents
    spec:
      automountServiceAccountToken: false
      containers:
{{ include "dsk.node-agent" . | indent 8 }}
{{ include "dsk.container-agent" . | indent 8 }}
      volumes:
{{ toYaml .Values.default.volumes | indent 8 }}
        {{- if eq .Values.dataSaker.runtimeType "docker" }}
        - name: docker
          hostPath:
            path: /var/lib/docker
        {{- else }}
        - name: containerd
          hostPath:
            path: /var/run/containerd
        {{- end }}
        - name: agent-configs
          configMap:
            name: node-agent-configs
            items:
              - key: node-agent-config.yml
                path: node-agent-config.yml
              - key: container-agent-config.yml
                path: container-agent-config.yml
        - name: rootfs
          hostPath:
            path: /
            type: ""
        - name: proc
          hostPath:
            path: /proc
            type: ""
        - name: sys
          hostPath:
            path: /sys
            type: ""
        - name: var-run
          hostPath:
            path: /var/run
        - name: disk
          hostPath:
            path: /dev/disk
---