{{- if gt (len .Values.dataSaker.postgresAgent.list) 0 -}}
{{ $agentKind := .Values.dataSaker.postgresAgent.kind }}
{{ $registryAddr := .Values.dataSaker.registryAddr }}
{{ $namespace := .Release.Namespace }}
{{ $clusterId := .Values.dataSaker.clusterId }}
{{ $apiKey := .Values.dataSaker.apiKey }}
{{ $metricDataGate := .Values.dataSaker.metricDataGate }}
{{ $agentManager := .Values.dataSaker.agentManager }}
{{ $agentManagerBaseUrl := .Values.dataSaker.agentManagerBaseUrl }}
{{ $volumes := .Values.default.volumes}}
{{ $volumeMounts := .Values.default.volumeMounts}}
{{ $metricConfig := .Values.default.metricConfig}}
{{- range $obj := .Values.dataSaker.postgresAgent.list }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $agentKind }}-{{ $obj.name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: {{ $agentKind }}-{{ $obj.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: datasaker
      app: {{ $agentKind }}-{{ $obj.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datasaker
        app: {{ $agentKind }}-{{ $obj.name }}
    spec:
      containers:
        - name: dsk-postgres-agent
          image: "{{ $registryAddr }}/{{ $agentKind }}:{{ $obj.imgVersion }}"
          imagePullPolicy: {{ $obj.imgPolicy }}
          resources:
{{ toYaml $obj.resources | indent 12 }}
          env:
            - name: DATA_SOURCE_USER
              value: {{ $obj.user }}
            - name: DATA_SOURCE_PASS
              value: {{ $obj.pass }}
            - name: DATA_SOURCE_URI
              value: {{ $obj.targetAddr }}/{{ $obj.database }}?sslmode=disable
            - name: DSK_SUB_KIND
              value: {{ $obj.name }}
            - name: DSK_LOG_LEVEL
              value: {{ $obj.logLevel }}
            - name: DSK_GLOBAL_APIKEY
              value: {{ $apiKey }}
            - name: DSK_GLOBAL_GATEWAY_URL
              value: {{ $metricDataGate }}
            - name: DSK_GLOBAL_AGENTMANAGER_URL
              value: {{ $agentManager }}
            - name: DSK_GLOBAL_AGENTMANAGER_BASE_URL
              value: {{ $agentManagerBaseUrl }}
          volumeMounts:
{{ toYaml $volumeMounts | indent 12 }}
            - name: agent-config
              subPath: agent-config.yml
              mountPath: "/datasaker/dsk-postgres-agent/agent-config.yml"
      volumes:
{{ toYaml $volumes | indent 8 }}
        - name: agent-config
          configMap:
            name: {{ $agentKind }}-{{ $obj.name }}
            items:
              - key: agent-config.yml
                path: agent-config.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $agentKind }}-{{ $obj.name }}
  namespace: {{ $namespace }}
  labels:
    app.kubernetes.io/name: datasaker
    app: {{ $agentKind }}-{{ $obj.name }}
data:
  agent-config.yml: |
    metric:
      scrape_interval: 15s
      scrape_timeout: 5s
      external_labels:
        cluster_id: {{ $clusterId }}
      scrape_configs:
        - job_name: 'dsk-postgres-agent'
          url: localhost:9187
{{ toYaml $metricConfig | indent 10 }}
---
{{- end }}
{{- end -}}
